# action.yml
name: 'APIMATIC Transformer'
description: 'Convert API Specifications to different formats'
inputs:
  auth:
    description: 'Basic Authorization of user'
    required: true
    default: 1
outputs:
  specurl:
    description: 'Download URL for converted API Specification in the required format'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.auth }}
