# action.yml
name: 'APIMATIC Transformer'
description: 'Convert API Specifications to different formats'
inputs:
  auth:
    description: 'Basic Authorization of user'
    required: true
    default: 1
    inputURL:
    description: 'Input API Specification URL'
    required: true
    default: 1
    exportFormat:
    description: 'Required Format of API Specification'
    required: true
    default: 1
outputs:
  specurl:
    description: 'Download URL for converted API Specification in the required format'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.auth }}
    - ${{ inputs.inputURL }}
    - ${{ inputs.exportFormat }}
