name: 'APIMATIC Transformer'
description: 'Convert API Specifications to required API Specifcation Format'
inputs:
  auth:
    description: 'Basic Authorization of user'
    required: true
  inputURL:
    description: 'Input API Specification URL'
    required: true
  exportFormat:
    description: 'Required Format of API Specification'
    required: true
outputs:
  specurl:
    description: 'Download URL for converted API Specification in the required format'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.auth }}
    - ${{ inputs.inputURL }}
    - ${{ inputs.exportFormat }}
