on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: Auth
        with:
         auth: ${{ secrets.AUTH }}
     # Use the pokemon_name output from our action (id:pokemon)
      - name: Get the API Spec UR
        run: echo "${{ steps.Auth.outputs.specurl }}"
