name: APITransformer
on: [push]

jobs:
  Test_Transformer:
    runs-on: ubuntu-latest
    name: Testing API Transformer Action
    steps:
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Transform API Spec
        uses: ./ # Uses an action in the root directory
        id: transform
        with:
         auth: ${{ secrets.AUTH }}
         inputURL: 'https://petstore.swagger.io/v2/swagger.json'
         exportFormat: 'raml'
     # Use the Transformed API Spec as output from our action (id:transform)
      - name: Get the API Spec UR
        run: echo "${{ steps.transform.outputs.specurl }}"
